apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "chart-cloud.name" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "chart-cloud.name" . }}-mysql
    helm.sh/chart: {{ include "chart-cloud.name" . }}-mysql
    app.kubernetes.io/instance: {{ .Release.Name }}-mysql
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart-cloud.name" . }}-mysql
      app.kubernetes.io/instance: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart-cloud.name" . }}-mysql
        app.kubernetes.io/instance: {{ .Release.Name }}-mysql
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.mysql.image.repository }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
# {{- if .Values.globalEnvironments.enabled }}
#         env:
# {{ toYaml .Values.globalEnvironments.environments | indent 8 }}
#         - name: MYSQL_HOST
#           value: {{ .Values.mysql.service.serviceName }}
# {{- end }}
{{- if .Values.globalEnvironments.enabled }}
        env:
{{ toYaml .Values.globalEnvironments.environments | indent 8 }}
{{- end }}
        ports:
          - name: http
            containerPort: 3306
            protocol: TCP

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http

{{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets.allSecrets | indent 8 }}
{{- end }}
