apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: ubuntu
  labels:
    name: ubuntu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: murodbey/ubuntuimage
        stdin: true
        tty: true
      imagePullSecrets:
      - name: docker-registry-secret

