apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app
  type: NodePort
  ports:
  - name: http
    nodePort: 31013
    port: 80
    targetPort: 80
    protocol: TCP
